### ISSUE TITLE
ucp option not working as expected

### ISSUE THREAD

**Issue by wdiestel** [SWI-Prolog/packages-pcre#4]
The ucp option has no effect. In the following test the second and third query should both result in 'false'.

```
Welcome to SWI-Prolog (threaded, 64 bits, version 8.4.1)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- pcre:re_match('\\bfranda\\b','frandaĵo',[ucp(false)]).
true.

?- pcre:re_match('\\bfranda\\b','frandaĵo',[ucp(true)]).
true.

?- pcre:re_match('(*UCP)\\bfranda\\b','frandaĵo',[]).
false.
```

**Comment by JanWielemaker** [comment]
As is, re_match/3 only accepts _matching_ options.   Compilation options can be passed as flags to the regex.  ucp is not supported by these flags though.  This implies this works:

```
?- re_compile('\\bfranda\\b', Re, [ucp(true)]),
    re_match(Re, 'frandaĵo').
false.
```
It is not totally trivial how to improve on that.    Splitting the options would work, but would also (I fear) seriously reduce the performance of re_match/3.   Adding a flag could be an option.  I'd prefer to stick to the "standard" flags though.   Possibly the last example is how it should work.

**Comment by wdiestel** [comment]
Hello Jan,

I think then it is ok as it is. Seems I did not really understand it from documentation. The workaround with the prefix I finally found reading through the linked lib docs. I‘m using SWI‘s docker image in my current work. 

So may be just some additional hint how to work with Unicode strings/ UCP correctly would new users save some time and trouble. 

Kind regards,
Wolfram.

**Comment by wdiestel** [comment]
I let a comment relating ucp at the re_match docs: https://eu.swi-prolog.org/pldoc/doc_for?object=re_match/2

So I think the issue could be closed.

Kind regards,
   Wolfram.
