### ISSUE TITLE
How to set option PCRE_JAVASCRIPT_COMPAT?

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-pcre#5]
I'm trying to set PCRE option `PCRE_JAVASCRIPT_COMPAT` (this corresponds to option `PCRE2_MATCH_UNSET_BACKREF` in PCRE2).

This option is needed for XPath 3.1 regex matching.  For example, calling `re_replace('(ab)|(c)', '[1=$1][2=$2]', "abc", X)` should succeed in XPath with `X="[1=ab][2=]cd"`.  Since there is no second match for the pattern, the second backref (`$2`) is replaced by the empty string.

The SWI library allows this option to be set with `compat(javascript)` in predicate `re_compile/3`.  This predicate creates a regex blob that has an unclear purpose.  Predicate `re_replace/4` does not accept such a regex blob, emitting a type error (text expected) when tried.

There is a small collection of single character flags that can be specified in `re_replace/4`, but none of these maps onto option `compat(javascript)`:

```prolog
re_flag_option_(i, caseless(true)).
re_flag_option_(m, multiline(true)).
re_flag_option_(x, extended(true)).
re_flag_option_(s, dotall(true)).
re_flag_option_(a, capture_type(atom)).
re_flag_option_(r, capture_type(range)).
re_flag_option_(t, capture_type(term)).
```
[source location](https://github.com/SWI-Prolog/packages-pcre/blob/master/pcre.pl#L578-L584)

I have the following 2 questions:
1. How to enable option `PCRE_JAVASCRIPT_COMPAT` in this library?
2. What is the purpose of the regex blob that `re_compile/3` produces?  If this blob cannot be used by other public predicates in the library then `re_compile/3` should maybe be private.  If some other public predicate can use the regex blob, then the `Regex` parameters should distinguish between `Regex:blob` and `Regex:pattern` (I do not know the SWI type for non-blob patterns).

**Comment by JanWielemaker** [comment]
> 2\. What is the purpose of the regex blob that `re_compile/3` produces?

It is used by e.g., re_match and a few of the others that have type Regex as argument and where you can provide a pattern[+flags] or a blob.   re_replace examines the pattern though and doesn't support this.   The flags are based on established practices (don't recall where I got them).

I guess it is possible to make re_replace, etc. accept the blobs.  Alternatively we could add some notation that allows the / with any of the options, e.g., `Pattern/[key(value),...]`

**Comment by kamahen** [comment]
I have some new code that tests things better. You can get it from this PR (warning - work-in-progress and not yet reviewed): https://github.com/SWI-Prolog/packages-pcre/pull/3
There's an internal predicate that might help: pcre:'$re_compile_options'(Options, Str).

I've noticed some places where compilation doesn't happen the way I expect. Until I figure out whether this is a bug or a feature, I recommend that you always use re_compile/3 and don't depend on re_replace/4, re_matchsub/4, etc. to do the compilation for you. But -- as you say -- re_replace/4 doesn't take an `regex` blob ... I'll take a look at it.

**Comment by kamahen** [comment]
My last comment wasn't very clear ... let me start again.

PR #3 *should* be compatible with the current code (except for bug fixes) but it's become quite a bit larger than I had originally expected. It's up to @JanWielemaker when to merge it -- and I'd still need to do a bit more work to get compat(javascript) working for re_replace. I'm not sure how long this will take -- there are quite a few corner cases and I've ended up doing rather more refactoring than I had originally intended. Also, there still aren't enough test cases.

If you have some javascript-compatible test cases, that would help me.

I've been mainly concentrating on re_config/1, re_compile/3, and the various options. For some predicates (e.g., re_matchsub), when a string is given as the Regex, it appears from reading the code that in some situations, some of the options aren't properly processed. So, I need to add some debugging to figure out what's going on, and also make some test cases to verify (also will probably add some more debugging predicates to verify the exact option bits that are being set). I'll also have to do this with re_replace/4 and other predicates, it seems.

It'll probably take a few days for me to get compat(javascript) working properly with re_replace/4; but it could take me longer (or less time); I haven't looked much at that code, assuming that it wouldn't need any changes.

(My plan was to make two PRs: one with the PCRE1 changes and a second one that's a "minimal" set of changes to make it all work with PCRE2. The 2nd PR is "mostly done", except for the different set of options, and the test cases.)

**Comment by kamahen** [comment]
Part of the problem seems to be that the flags for `re_replace/5` and `re_split/{3,4}` are a bit different from those for the other predicates. In addition, the regex for these predicates requires `capture_type(range)`, so another way might be desired for specifying the resulting type for `re_replace/5` and the types of the pieces `re_split/{3,4}` (currently these are only done by flags to the Regex, not options).

We should probably make these changes:
* add an `Options` parameter to `re_replace/5' (making it `re_replace/6`), to allow things such as `compat(javascript)`.
* add `re_compile_replace/3` and `re_compile_split/3` and modify `re_replace/{5,6}` and `resplit/{3,4}` to accept its compiled result. 

Making these changes shouldn't be difficult but it will take a bit of time because of the various corner cases and the need for more test cases. Also, I'd want to make the changes on top of my PR because I don't want to do the changes twice. So, I'd need @JanWielemaker to agree to merging PR #3 when I finish the changes to allow `compat(javascript)` etc. with `re_replace/5` (and maybe `re_replace/6`). Otherwise, I'd like to delay making the changes until after I've finished the migration to PCRE2.

**Comment by kamahen** [comment]
Issue #7 needs to be fixed first.

**Comment by kamahen** [comment]
@wouterbeek - I've just pushed https://github.com/SWI-Prolog/packages-pcre/commit/7bc022cae02dca66807ead667e88b72e00b946ae , which should let you set compat(javascript) and other options. There are still some bugs in the code -- I think they're all related to setting the global `capture_type`. You can see these by looking at the `fixme` tests in test_pcre.pl.

Do you have any tests that I can add to test_pcre.pl? The test suite isn't nearly comprehensive enough; but I'd like to move on to the PCRE2 migration (as soon as I fix the global `capture_type` bugs).

**Comment by kamahen** [comment]
(The change is also available here: https://github.com/SWI-Prolog/packages-pcre/pull/3/commits/7bc022cae02dca66807ead667e88b72e00b946ae)

It's part of a PR that I need to discuss with @JanWielemaker as to when it can be merged into the swipl-devel master.

**Comment by wouterbeek** [comment]
@kamahen Thanks for working on this!  I have 2 tests (`test2` and `test3`) that currently fail but should succeed according to the XPath standard:

```prolog
:- use_module(library(debug)).
:- use_module(library(pcre)).

% Example of a case that succeeds.
test1 :-
  re_replace("^(.*?)d(.*)$", "$1c$2", "darted", X),
  assertion(X == "carted").

% Cannot be specified in the SWI library
% <https://github.com/SWI-Prolog/packages-pcre/issues/5>.
%
% I'm not sure why "cd" appears after the "]", but this is how it is
% specified in the XPath standard:
% <https://www.w3.org/TR/xpath-functions/#func-replace>
test2 :-
  re_replace("(ab)|(a)", "[1=$1][2=$2]", "abcd", Y),
  assertion(Y == "[1=ab][2=]cd").

% The underlying PCRE2 library allows multiple uses of the same
% backreference to a group, but this does not yet work in the SWI
% library <https://github.com/SWI-Prolog/packages-pcre/issues/6>.
test3 :-
  re_replace("a(.)", "a$1$1", "abracadabra", Z),
  assertion(Z == "abbraccaddabbra").
```

**Comment by kamahen** [comment]
I'll look into those -- I don't see any reason why they should need PCRE2 to work; they seem to be due to some limitation in the pcre.pl code -- but I was also hoping for an example where you require a compile option that can't be specified by the re_replace flags (e.g., `compat(javascript)`).

**Comment by wouterbeek** [comment]
@kamahen I think that `test2` requires setting the JavaScript flag, see <https://github.com/SWI-Prolog/packages-pcre/issues/5>.

`test3` indeed does not depend on compile flags and may be entirely fixed in Prolog.

**Comment by kamahen** [comment]
There's no "replace" function in PCRE1, so pcre.pl has its own mechanism for finding the pieces to replace and then uses the `With` argument (which it parses) to create the string with replacements. 
For `test2`, I get the same result both with and without `compat(javascript)` in the code I'm developing:
```
?- re_matchsub("(ab)|(a)", "abcd", Y, [compat(javascript)]).
Y = re_match{0:"ab", 1:"ab"}.

?- re_matchsub("(ab)|(a)", "abcd", Y, []).
Y = re_match{0:"ab", 1:"ab"}.
```
Of course, it's possible that I haven't properly handled `compat(javascript)` ... I'll look into this further.

For reference, here's the test:
```
re_replace("(ab)|(a)", "[1=$1][2=$2]", "abcd", Y, [compat(javascript)]).
```

**Comment by kamahen** [comment]
About `test2` -- as far as I can tell, PCRE1 only creates a single "capture" for the regexp `(ab)|(a)`, so `[2=$2]` is in error. `compat(javascript)` doesn't seem to change this. I haven't yet tried this with PCRE2, but I suspect it'll be the same.

Anyway, `(ab)|(a)` doesn't really make sense -- it should be written `(ab|a)`, I think.

(Sorry for being so slow in responding -- I've been sick (not COVID). I'm almost ready to release my changes for PCRE1 (just "one more thing to fix"); the PCRE2 -based code is also passing most of the tests, so it shouldn't be much more work to have a PCRE2 implementation that has the same capabilities as the current PCRE1-based code -- adding in all the PCRE2 features will take longer, so I plan on an initial release of the PCRE2-based code, followed by another that supports its additional functionalities.)

**Comment by kamahen** [comment]
PS: @wouterbeek wrote
```
% I'm not sure why "cd" appears after the "]", but this is how it is
% specified in the XPath standard:
```
The `"cd"` appears because the original string is `"abcd"` and the pattern `"(ab)|(a)"` matches the initial `"ab"`.

**Comment by kamahen** [comment]
Javascript treats a missing replacement reference as ordinary characters (whereas my `re_replace/{4,5}` code throws an `existence_error(key,_,_),_)`. For example:
```javascript
> "abcd".replace(/(ab)/, "[1=$1][2=$3]")
'[1=ab][2=$3]cd'
```
Because there's no `javascript` compatibility in PCRE2, I don't intend to change the behavior of `re_replace/{4,5}`. I'm leaving this as a "blocked" test for now. Note that there are related `PCRE2_MATCH_UNSET_BACKREF` and `PCRE2_SUBSTITUTE_UNKNOWN_UNSET` options (the latter seems to be Javascript's default behavior; and I haven't tested how missing backrefs in patterns behave).

Also, there's example `pcre2_substitute()` code here (I haven't tried it yet): https://cpp.hotexamples.com/examples/-/-/pcre2_substitute/cpp-pcre2_substitute-function-examples.html

BTW, the example from the Xpath standard behaves identically in Javascript:
```javascript
> "abcd".replace(/(ab)|(a)/, "[1=$1][2=$2]")
"abcd".replace(/(ab)|(a)/, "[1=$1][2=$2]")
'[1=ab][2=]cd'
```

**Comment by kamahen** [comment]
It wouldn't surprise me if this gets treated different by PCRE2, so I think I'll leave things as-is. Also, implementing `re_replace` using `pcre2_substitute` doesn't look too difficult, so I might do that (but, for backwards compatibility, name it `re_substitute` and leave the current `re_replace` as-is but deprecated).
For the record, this is how things are done right now (PCRE1):
```
?- re_replace("(ab)|(a)", "[1=$1][2=$1]", "abcd", New).
New = "[1=ab][2=ab]cd".

?- re_replace("(ab)|(a)", "[1=$1][2=$2]", "acd", New).
New = "[1=][2=a]cd".

?- re_replace("(ab)|(a)", "[1=$1][2=$1]", "acd", New).
New = "[1=][2=]cd".

?- re_replace("(ab)|(a)", "[1=$1][2=$2]", "abcd", New).
ERROR: key `2' does not exist in re_match{0:0-2,1:0-2}
```

**Comment by JanWielemaker** [comment]
I'm running with the current branch for a while.  Runs fine.   I'd propose to cleanup this, merge it into master and then move to pcre2 before dealing with these details.

**Comment by kamahen** [comment]
A cleanup and rebase -i are my intentions. I just wanted to document some of the details that relate to this issue.

I'm rather busy with other things, so it'll probably take me a few weeks to put together the final PR (the main things to update are the option lists and verify the documentation one more time).

**Comment by kamahen** [comment]
`compat(javascript)` is now accepted with all the predicates (https://github.com/SWI-Prolog/packages-pcre/commit/fe4775da69735285c4461ff2d3aa137b783fdabf or earlier).
I'm leaving this item open, as a reminder to check behavior with PCRE2.

**Comment by kamahen** [comment]
Closing this because it's a PCRE2 issue - you might wish to file a bug report there, about this discrepancy between "Perl regular expressions" and Javascript.

**Comment by kamahen** [comment]
@JanWielemaker - please close this.
