### ISSUE TITLE
Multiple uses of the same backreference

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-pcre#6]
PCRE allows more than one back reference (written as two words in PCRE documentation) to the same subpattern:

> There may be more than one back reference to the same subpattern. ([Source](https://www.pcre.org/original/doc/html/pcrepattern.html#SEC19)

PCRE2 also allows this, but uses "backreference" (one word) i.o. "back reference" (two words) and uses "group" i.o. "subpattern":

> There may be more than one backreference to the same group. ([Source](https://www.pcre.org/current/doc/html/pcre2pattern.html#SEC19))

In the SWI library, backreferences are placed into a dict, which throws an error because dicts do not allow multiple occurrence of the same key: [relevant code line](https://github.com/SWI-Prolog/packages-pcre/blob/master/pcre.pl#L404)

**Comment by JanWielemaker** [comment]
> In the SWI library, backreferences are placed into a dict, which throws an error because dicts do not allow multiple occurrence of the same key: [relevant code line](https://github.com/SWI-Prolog/packages-pcre/blob/master/pcre.pl#L404)

Considering dicts are rather comfortable and efficient I propose to keep these.  Next we either accept the limitation or define to create a list of values for the same key.

**Comment by kamahen** [comment]
The number of keys is quite small, so I doubt that efficiency of lookup matters.

Anyway, PCRE2 provides `pcre2_substitute()`, so it might make sense to reimplement `re_replace/4` using it.

**Comment by kamahen** [comment]
I traced through the code, and it appears to be easy to fix.

Question: the current code fails if there's a name in `With` that isn't in the pattern. I propose changing this to throwing an error.

Also, there doesn't seem to be an escape for "`$`" or "`\`" - I propose allowing these to be doubled as escapes (pcre2 seems to only have "`$`" for substitution; and it uses "`$$`" for a single dollar sign). Another possibility is "`${}`".
There are some inconsistencies between pcre2 replacement and the current re_replace ... I wonder what the best approach is?
https://www.pcre.org/current/doc/html/pcre2api.html#substitutions
(Python seems to only use "`\`" and numbers: https://docs.python.org/3/library/re.html?highlight=re%20sub#re.sub)

**Comment by kamahen** [comment]
BTW, the main change shouldn't make things slower; the main change would be to replace
```
Skel :< Dict
```
by something similar to
```
maplist(dict_pair_lookup(Dict), Skel)
```
where:
```
dict_pair_lookup(Dict, Key-Dict.Key).
```

**Comment by JanWielemaker** [comment]
As I understand PCRE2 provides support for replace I'd just leave the replace unmodified for the PCRE1 version and implement it properly for PCRE2.  That will bring some incompatibilities in extreme cases.   I think we can live with that.

**Comment by kamahen** [comment]
I wasn't planning on using `pcre2_substitute()`, at least not initially; and if I did, I'd leave the current `re_replace/4` in place, for backward compatibility. FWIW, PHP doesn't use `pcre2_substitute()` either -- I don't know why, so I'd need to do a bit of research to figure out if there are problems with using `pcre2_substitute()`. [Python seems to have its own implement of regexps (in a mixture of Python and C); and I don't know what nodejs does]

Unless anyone objects, I'll modify `re_replace/4` to allow multiple uses of the same back reference and throw an error if a name is used that isn't defined, and also allow `$$` and `\\` escapes. (But first I need to fix a couple of bugs with the name lookup code that have slipped through because of insufficient test cases.)

**Comment by kamahen** [comment]
Fixed: https://github.com/SWI-Prolog/packages-pcre/pull/3/commits/49e811c6917d1ad67fd15cd7e3574974e9665cf8

**Comment by kamahen** [comment]
This has been fixed and is in the "devel" release.
@JanWielemaker - Please close this issue.
