### ISSUE TITLE
global capture_type is ignored 

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/packages-pcre#8]
```
?- re_matchsub('(a+)(b+)(c+)', 'xabc', Subs, [extended(true), capture_type(range)]).
Subs = re_match{0:"abc", 1:"a", 2:"b", 3:"c"}.
```
However, the behavior is correct if the pattern is compiled:
```
?- re_compile('(a+)(b+)(c+)', Re, [capture_type(range)]), re_matchsub(Re, 'xabc', Subs, []).
Re = <regex>(0x55b5bbbe1900),
Subs = re_match{0:1-3, 1:1-1, 2:2-1, 3:3-1}.
```

**Comment by JanWielemaker** [comment]
That is (again) because flags affect the compilation and options the execution (I think).    Considering the number of options pcre has there is much to say for using a proper options (rather than invent a whole lot of new flags).

**Comment by kamahen** [comment]
I think it makes sense for re_compile/3 to also allow flags (it's the only predicate that doesn't allow flags; re_match/3 and re_matchsub/4 already allow both flags and options (but have a bug; see below). This is probably less confusing for the user because the flags and options cover 4 situations: compile-time (e.g., `caseless`), execution-time (e.g., `optimize`), wrapper-specific (e.g., `capture_type`); and some of them can apply to both compile-time and execution-time (e.g., `anchored`).

And I propose that the flags take precedence. E.g.,
```
re_compile('a'/i, Re, [caseless(false)])
```
would result in caseless matching (the `caseless(false)` in the options would be superseded by the `i` flag).

Currently, this doesn't work as expected:
```
re_matchsub('c', "ABC", Sub, [caseless(true)]).
```
but instead has to be specified:
```
re_matchsub('c'/i, "ABC", Sub, []).
```

**Comment by kamahen** [comment]
Believed to be fixed with https://github.com/SWI-Prolog/packages-pcre/commit/fe4775da69735285c4461ff2d3aa137b783fdabf (or an earlier commit).
